/**
 * PKCE (Proof Key for Code Exchange) Utilities
 * 
 * Per OAuth 2.0 RFC 6749 Section 4.2
 */

/**
 * Generate a random 128-character PKCE code verifier
 * Uses cryptographically secure random number generator
 */
export function generatePKCEVerifier(): string {
  const array = new Uint8Array(64)
  crypto.getRandomValues(array)
  return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('')
}

/**
 * Generate SHA-256 code challenge from verifier
 * 
 * @param verifier - The code verifier generated by generatePKCEVerifier()
 * @returns Base64URL-encoded SHA-256 hash
 */
export async function generatePKCEChallenge(verifier: string): Promise<string> {
  const encoder = new TextEncoder()
  const data = encoder.encode(verifier)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const hashArray = Array.from(new Uint8Array(hashBuffer))
  const hashBase64 = btoa(String.fromCharCode(...hashArray))
  return hashBase64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

/**
 * Generate a random state parameter for CSRF protection
 * Should be stored in sessionStorage and validated on callback
 */
export function generateState(): string {
  const array = new Uint8Array(32)
  crypto.getRandomValues(array)
  return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('')
}

/**
 * Generate cryptographically secure random string
 * 
 * @param length - Number of bytes (default: 32)
 * @returns Hex-encoded random string
 */
export function generateSecureRandom(length: number = 32): string {
  const array = new Uint8Array(length)
  crypto.getRandomValues(array)
  return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('')
}

/**
 * Store PKCE context in sessionStorage
 * 
 * @param verifier - The code verifier
 * @param state - The CSRF state
 * @param returnUrl - Where to redirect after authentication
 */
export function storePKCEContext(verifier: string, state: string, returnUrl?: string): void {
  sessionStorage.setItem('pkce_verifier', verifier)
  sessionStorage.setItem('pkce_state', state)
  if (returnUrl) {
    sessionStorage.setItem('return_url', returnUrl)
  }
}

/**
 * Retrieve PKCE context from sessionStorage
 */
export interface PKCEContext {
  verifier: string | null
  state: string | null
  returnUrl: string | null
}

export function getPKCEContext(): PKCEContext {
  return {
    verifier: sessionStorage.getItem('pkce_verifier'),
    state: sessionStorage.getItem('pkce_state'),
    returnUrl: sessionStorage.getItem('return_url'),
  }
}

/**
 * Clear PKCE context from sessionStorage
 */
export function clearPKCEContext(): void {
  sessionStorage.removeItem('pkce_verifier')
  sessionStorage.removeItem('pkce_state')
  sessionStorage.removeItem('return_url')
}
